.\" Copyright (c) 2006 Stijn van Dongen
.TH "mcxarray" 1 "27 Feb 2006" "mcxarray 1\&.006, 06-058" "USER COMMANDS "
.po 2m
.de ZI
.\" Zoem Indent/Itemize macro I.
.br
'in +\\$1
.nr xa 0
.nr xa -\\$1
.nr xb \\$1
.nr xb -\\w'\\$2'
\h'|\\n(xau'\\$2\h'\\n(xbu'\\
..
.de ZJ
.br
.\" Zoem Indent/Itemize macro II.
'in +\\$1
'in +\\$2
.nr xa 0
.nr xa -\\$2
.nr xa -\\w'\\$3'
.nr xb \\$2
\h'|\\n(xau'\\$3\h'\\n(xbu'\\
..
.if n .ll -2m
.am SH
.ie n .in 4m
.el .in 8m
..
.SH NAME
mcxarray \- Transform array data to MCL matrices
.SH SYNOPSIS

\fBmcxarray\fP [options] <array data matrix>

\fBmcxarray\fP
\fB[-o\fP fname (\fIoutput file fname\fP)\fB]\fP
\fB[-co\fP num (\fIcutoff for output values\fP)\fB]\fP
\fB[-gq\fP num (\fIignore input smaller than\fP)\fB]\fP
\fB[-lq\fP num (\fIignore input larger than\fP)\fB]\fP
\fB[-t\fP (\fIwork with the transpose\fP)\fB]\fP
\fB[-ctr\fP num (\fIadd center (for graph-type input)\fP)\fB]\fP
\fB[--ctr\fP (\fIadd center with default value (for graph-type input)\fP)\fB]\fP
\fB[--01\fP (\fIremap output to [0,1] interval\fP)\fB]\fP
\fB[--cosine\fP (\fIuse cosine\fP)\fB]\fP
\fB[--pearson\fP (\fIuse Pearson correlation (default)\fP)\fB]\fP
\fB[-tear\fP num (\fIinflate input columns\fP)\fB]\fP
\fB[-teartp\fP num (\fIinflate tranposed columns\fP)\fB]\fP
\fB[-pi\fP num (\fIinflate the result\fP)\fB]\fP
<fname> (\fIarray data matrix\fP)
.SH DESCRIPTION
\fBmcxarray\fP reads a data file satisfying the mcl input format
(refer to \fBmcxio(5)\fP)\&. By default it will work with the
columns as the data vectors (note that mcl matrices are
presented as a listing of columns)\&. This can be changed using
the \fB-t\fP option\&.
.SH OPTIONS

.ZI 3m "\fB-o\fP fname (\fIoutput file fname\fP)"
\&
.br
Indeed\&.
.in -3m

.ZI 3m "\fB-co\fP num (\fIcutoff for output values\fP)"
\&
.br
Output values smaller than \fInum\fP are removed (set to zero)\&.
.in -3m

.ZI 3m "\fB-gq\fP num (\fIignore input smaller than\fP)"
\&
.br
Input values smaller than \fInum\fP are ignored\&.
.in -3m

.ZI 3m "\fB-lq\fP num (\fIignore input larger than\fP)"
\&
.br
Input values larger than \fInum\fP are ignored\&.
.in -3m

.ZI 3m "\fB-t\fP (\fIwork with the transpose\fP)"
\&
.br
Work with the transpose of the input data matrix\&.
.in -3m

.ZI 3m "\fB-ctr\fP num (\fIadd center (for graph-type input)\fP)"
\&
.br
Add diagonal values to the output according to a (so called)
\fIcenter\fP formula\&.
.in -3m

.ZI 3m "\fB--ctr\fP (\fIadd center with default value (for graph-type input)\fP)"
\&
.br
Same as \fB-ctr\fP\ \&\fB1\&.0\fP\&.
.in -3m

.ZI 3m "\fB--01\fP (\fIremap output to [0,1] interval\fP)"
\&
.br
Rescale output values so that they are within the [0,1] interval\&.
.in -3m

.ZI 3m "\fB--cosine\fP (\fIuse cosine\fP)"
\&
.br
Use the cosine as correlation measure\&.
.in -3m

.ZI 3m "\fB--pearson\fP (\fIuse Pearson correlation (default)\fP)"
\&
.br
Compute the Pearson correleation coefficient as the
similarity between the data columns\&.
.in -3m

.ZI 3m "\fB-tear\fP num (\fIinflate input columns\fP)"
\&
.br
Apply (column-wise) inflation with parameter \fInum\fP to the input
values before further processing\&.
.in -3m

.ZI 3m "\fB-teartp\fP num (\fIinflate tranposed columns\fP)"
\&
.br
Apply (column-wise) inflation with parameter \fInum\fP to the input
values in the transposed matrix before further processing\&.
.in -3m

.ZI 3m "\fB-pi\fP num (\fIinflate the result\fP)"
\&
.br
Apply inflation with parameter \fInum\fP to the output values\&.
.in -3m
.SH AUTHOR

Stijn van Dongen\&.
.SH SEE ALSO
\fBmcl(1)\fP,
\fBmclfaq(7)\fP,
and \fBmclfamily(7)\fP for an overview of all the documentation
and the utilities in the mcl family\&.
