.\" Copyright (c) 2009 Stijn van Dongen
.TH "mcxarray" 1 "4 Nov 2009" "mcxarray 1\&.008, 09-308" "USER COMMANDS "
.po 2m
.de ZI
.\" Zoem Indent/Itemize macro I.
.br
'in +\\$1
.nr xa 0
.nr xa -\\$1
.nr xb \\$1
.nr xb -\\w'\\$2'
\h'|\\n(xau'\\$2\h'\\n(xbu'\\
..
.de ZJ
.br
.\" Zoem Indent/Itemize macro II.
'in +\\$1
'in +\\$2
.nr xa 0
.nr xa -\\$2
.nr xa -\\w'\\$3'
.nr xb \\$2
\h'|\\n(xau'\\$3\h'\\n(xbu'\\
..
.if n .ll -2m
.am SH
.ie n .in 4m
.el .in 8m
..
.SH NAME
mcxarray \- Transform array data to MCL matrices
.SH SYNOPSIS

\fBmcxarray\fP [options]

\fBmcxarray\fP
\fB[-data\fP fname (\fIinput data file\fP)\fB]\fP
\fB[-skipr\fP <num> (\fIskip <num> data rows\fP)\fB]\fP
\fB[-skipc\fP <num> (\fIskip <num> data columns\fP)\fB]\fP
\fB[-write-tab\fP <fname> (\fIwrite row labels to file\fP)\fB]\fP
\fB[-l\fP <num> (\fItake labels from column <num>\fP)\fB]\fP
\fB[-imx\fP fname (\fIinput matrix file\fP)\fB]\fP
\fB[-n\fP mode (\fInormalize input\fP)\fB]\fP
\fB[-o\fP fname (\fIoutput file fname\fP)\fB]\fP
\fB[-digits\fP <num> (\fIoutput precision\fP)\fB]\fP
\fB[--write-binary\fP (\fIwrite output in binary format\fP)\fB]\fP
\fB[-co\fP num (\fIcutoff for output values\fP)\fB]\fP
\fB[-cutoff\fP num (\fIcutoff for output values\fP)\fB]\fP
\fB[-gq\fP num (\fIignore input smaller than\fP)\fB]\fP
\fB[-lq\fP num (\fIignore input larger than\fP)\fB]\fP
\fB[--transpose\fP (\fIwork with the transposed data matrix\fP)\fB]\fP
\fB[--cosine\fP (\fIuse cosine\fP)\fB]\fP
\fB[--pearson\fP (\fIuse Pearson correlation (default)\fP)\fB]\fP
\fB[--spearman\fP (\fIuse Spearman rank correlation\fP)\fB]\fP
\fB[-pi\fP num (\fIinflate the result\fP)\fB]\fP
\fB[-tf\fP spec (\fIapply tf-spec to input matrix\fP)\fB]\fP
\fB[--help\fP (\fIprint this help\fP)\fB]\fP
\fB[-h\fP (\fIprint this help\fP)\fB]\fP
\fB[--version\fP (\fIprint version information\fP)\fB]\fP
.SH DESCRIPTION

\fBmcxarray\fP can either read a flat file containing array data (\fB-data\fP)
or a matrix file satisfying the mcl input format (\fB-imx\fP)\&. In the
former case it will by default work with the rows as the data vectors\&. In
the latter case it will by default work with the columns as the data
vectors (note that mcl matrices are presented as a listing of columns)\&.
This can be changed for both using the
\fB--transpose\fP option\&.
.SH OPTIONS

.ZI 2m "\fB-data\fP fname (\fIinput data file\fP)"
\&
.br
Specify the data file containing the expression values\&.
It should be tab-separated\&.
.in -2m

.ZI 2m "\fB-skipr\fP <num> (\fIskip <num> data rows\fP)"
\&
.br
Skip the first \fI<num>\fP data rows\&.
.in -2m

.ZI 2m "\fB-skipc\fP <num> (\fIskip <num> data columns\fP)"
\&
.br
Ignore the first \fI<num>\fP data columns\&.
.in -2m

.ZI 2m "\fB-l\fP <num> (\fItake labels from column <num>\fP)"
\&
.br
Specifies to construct a tab of labels from this data column\&.
The tab can be written to file using \fB-write-tab\fP\ \&\fIfname\fP\&.
.in -2m

.ZI 2m "\fB-write-tab\fP <fname> (\fIwrite row labels to file\fP)"
\&
.br
Write a tab file\&. In the simple case where the labels are in the first
data column it is sufficient to issue \fB-skipc\fP\ \&\fB1\fP\&.
If more data columns need to be skipped one must explicitly specify
the data column to take labels from with \fB-l\fP\ \&\fIl\fP\&.
.in -2m

.ZI 2m "\fB-imx\fP fname (\fIinput matrix file\fP)"
\&
.br
The expression values are read from a file in mcl matrix format\&.
.in -2m

.ZI 2m "\fB-n\fP mode (\fInormalization mode\fP)"
\&
.br
If \fImode\fP is set to \fBz\fP the data will be normalized
based on z-score\&. No other modes are currently supported\&.
.in -2m

.ZI 2m "\fB-o\fP fname (\fIoutput file fname\fP)"
\&
.br
Output file name\&.
.in -2m

.ZI 2m "\fB-digits\fP <num> (\fIoutput precision\fP)"
\&
.br
Specify the precision to use in native interchange format\&.
.in -2m

.ZI 2m "\fB--write-binary\fP (\fIwrite output in binary format\fP)"
\&
.br
Write output matrices in native binary format\&.
.in -2m

.ZI 2m "\fB-co\fP num (\fIcutoff for output values\fP)"
\&
'in -2m
.ZI 2m "\fB-cutoff\fP num (\fIalias for -co\fP)"
\&
'in -2m
'in +2m
\&
.br
Output values smaller than \fInum\fP are removed (set to zero)\&.
.in -2m

.ZI 2m "\fB-gq\fP num (\fIignore input smaller than\fP)"
\&
.br
Input values smaller than \fInum\fP are ignored\&.
.in -2m

.ZI 2m "\fB-lq\fP num (\fIignore input larger than\fP)"
\&
.br
Input values larger than \fInum\fP are ignored\&.
.in -2m

.ZI 2m "\fB--transpose\fP (\fIwork with the transpose\fP)"
\&
.br
Work with the transpose of the input data matrix\&.
.in -2m

.ZI 2m "\fB--cosine\fP (\fIuse cosine\fP)"
\&
'in -2m
.ZI 2m "\fB--pearson\fP (\fIuse Pearson correlation (default)\fP)"
\&
'in -2m
.ZI 2m "\fB--spearman\fP (\fIuse Spearman rank correlation\fP)"
\&
'in -2m
'in +2m
\&
.br
Use one of these to specify the correlation measure\&.
.in -2m

.ZI 2m "\fB-pi\fP num (\fIinflate the result\fP)"
\&
.br
Apply inflation with parameter \fInum\fP to the output values\&.
Transform the input matrix values according
to the syntax described in \fBmcxio(5)\fP\&.
.in -2m

.ZI 2m "\fB--help\fP (\fIprint help\fP)"
\&
'in -2m
.ZI 2m "\fB-h\fP (\fIprint help\fP)"
\&
'in -2m
'in +2m
\&
.br
.in -2m

.ZI 2m "\fB--version\fP (\fIprint version information\fP)"
\&
.br
.in -2m
.SH AUTHOR

Stijn van Dongen\&.
.SH SEE ALSO

\fBmcl(1)\fP,
\fBmclfaq(7)\fP,
and \fBmclfamily(7)\fP for an overview of all the documentation
and the utilities in the mcl family\&.
