.\" Copyright (c) 2009 Stijn van Dongen
.TH "mcx q" 1 "1 Jul 2009" "mcx q 1\&.008, 09-182" "USER COMMANDS "
.po 2m
.de ZI
.\" Zoem Indent/Itemize macro I.
.br
'in +\\$1
.nr xa 0
.nr xa -\\$1
.nr xb \\$1
.nr xb -\\w'\\$2'
\h'|\\n(xau'\\$2\h'\\n(xbu'\\
..
.de ZJ
.br
.\" Zoem Indent/Itemize macro II.
'in +\\$1
'in +\\$2
.nr xa 0
.nr xa -\\$2
.nr xa -\\w'\\$3'
.nr xb \\$2
\h'|\\n(xau'\\$3\h'\\n(xbu'\\
..
.if n .ll -2m
.am SH
.ie n .in 4m
.el .in 8m
..
.SH NAME
mcxq \- compute simple graph statistics
.SH SYNOPSIS

mcxq is not in actual fact a program\&. This manual
page documents the behaviour and options of the mcx program when
invoked in mode \fIq\fP\&. The options \fB-h\fP, \fB--apropos\fP,
\fB--version\fP, \fB-set\fP, \fB--nop\fP, \fB-progress\fP\ \&\fI<num>\fP
are accessible
in all \fBmcx\fP modes\&. They are described
in the \fBmcx\fP manual page\&.

\fBmcxq\fP
\fB[-imx\fP <fname> (\fIspecify matrix input\fP)\fB]\fP
\fB[-o\fP <fname> (\fIoutput file name\fP)\fB]\fP
\fB[--edge\fP (\fIlist simple edge statistics\fP)\fB]\fP
\fB[--edge-list\fP (\fIlist edge statistics per node\fP)\fB]\fP
\fB[--dim\fP (\fIonly list domain sizes\fP)\fB]\fP
\fB[-h\fP (\fIprint synopsis, exit\fP)\fB]\fP
\fB[--apropos\fP (\fIprint synopsis, exit\fP)\fB]\fP
\fB[--version\fP (\fIprint version, exit\fP)\fB]\fP
.SH DESCRIPTION

\fBmcxq\fP computes a number of simple statistics derived from the input
graph\&. Among these are the number of arcs, the node neighbour count
average, standard deviation, and median, and the edge weight
average, standard deviation, and median\&.

When instructed to, it can also compute other quantities related
to the input graph\&. See below\&.
.SH OPTIONS

.ZI 2m "\fB-imx\fP <fname> (\fIinput matrix\fP)"
\&
.br
The file name for input that is in mcl native matrix format\&.
.in -2m

.ZI 2m "\fB-o\fP <fname> (\fIoutput file name\fP)"
\&
.br
Set the name of the file where output should be written to\&.
.in -2m

.ZI 2m "\fB--edge\fP (\fIcompute simple statistics\fP)"
\&
.br
This is the default setting\&. If any other option (e\&.g\&. \fB--dim\fP)
is used, \fB--edge\fP has to be specified if this output mode is to
be activated in parallel\&.
.in -2m

.ZI 2m "\fB--edge-list\fP (\fIcompute simple statistics, node-wisel\fP)"
\&
.br
This outputs for each node its neighbour count and the average
weight of the edges connecting that node with those neighbours\&.
.in -2m

.ZI 2m "\fB--dim\fP (\fIonly list domain sizes\fP)"
\&
.br
This outputs the format (native interchange or native binary)
and the dimensions of the encoded matrix\&.
.in -2m
.SH SEE ALSO

\fBmcxio(5)\fP,
and \fBmclfamily(7)\fP for an overview of all the documentation
and the utilities in the mcl family\&.
